apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  labels:
    app: etcd
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: etcd
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: etcd
          image: "{{ .Values.etcd.image.repository }}:{{ .Values.etcd.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command:
            - etcd
            - --name=etcd0
            - --advertise-client-urls=http://etcd:2379
            - --listen-client-urls=http://0.0.0.0:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --data-dir=/var/lib/etcd
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          resources:
            {{- toYaml .Values.etcd.resources | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - etcdctl
                - endpoint
                - health
                - --endpoints=http://localhost:2379
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - etcdctl
                - endpoint
                - health
                - --endpoints=http://localhost:2379
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: etcd-data
              mountPath: /var/lib/etcd
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: "{{ .Values.etcd.persistence.size }}"
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: etcd
  ports:
    - name: client
      port: 2379
      targetPort: 2379
