apiVersion: v1
kind: Service
metadata:
  name: training-workers
  labels:
    app: training
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  selector:
    app: training
  ports:
    - name: ddp
      port: 29500
      targetPort: 29500
